# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Software-integeration-2\GUI\gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1475, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_3.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_15.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_15.addWidget(self.label_36)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_15.addWidget(self.label_33)
        self.et_user_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.et_user_name.setObjectName("et_user_name")
        self.verticalLayout_15.addWidget(self.et_user_name)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_15.addWidget(self.label_34)
        self.et_password = QtWidgets.QLineEdit(self.groupBox_3)
        self.et_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.et_password.setObjectName("et_password")
        self.verticalLayout_15.addWidget(self.et_password)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_15.addWidget(self.line_2)
        self.btn_login = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.verticalLayout_15.addWidget(self.btn_login)
        self.lb_result_login = QtWidgets.QLabel(self.groupBox_3)
        self.lb_result_login.setText("")
        self.lb_result_login.setObjectName("lb_result_login")
        self.verticalLayout_15.addWidget(self.lb_result_login)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lable_login_name = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lable_login_name.setFont(font)
        self.lable_login_name.setFrameShape(QtWidgets.QFrame.Box)
        self.lable_login_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lable_login_name.setObjectName("lable_login_name")
        self.verticalLayout.addWidget(self.lable_login_name)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cm_database = QtWidgets.QComboBox(self.groupBox)
        self.cm_database.setObjectName("cm_database")
        self.cm_database.addItem("")
        self.cm_database.addItem("")
        self.cm_database.addItem("")
        self.cm_database.addItem("")
        self.cm_database.addItem("")
        self.cm_database.addItem("")
        self.verticalLayout.addWidget(self.cm_database)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btn_process = QtWidgets.QPushButton(self.groupBox)
        self.btn_process.setObjectName("btn_process")
        self.verticalLayout.addWidget(self.btn_process)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_save_excel = QtWidgets.QPushButton(self.groupBox)
        self.btn_save_excel.setObjectName("btn_save_excel")
        self.verticalLayout.addWidget(self.btn_save_excel)
        self.btn_logout = QtWidgets.QPushButton(self.groupBox)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMaximumSize(QtCore.QSize(16777215, 1173))
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_18.addWidget(self.label_3)
        self.spinBox_offset = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_offset.setObjectName("spinBox_offset")
        self.verticalLayout_18.addWidget(self.spinBox_offset)
        self.label_45 = QtWidgets.QLabel(self.groupBox_4)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_18.addWidget(self.label_45)
        self.spinBox_limit = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_limit.setObjectName("spinBox_limit")
        self.verticalLayout_18.addWidget(self.spinBox_limit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.table_seelctall = QtWidgets.QTableWidget(self.tab_2)
        self.table_seelctall.setObjectName("table_seelctall")
        self.table_seelctall.setColumnCount(0)
        self.table_seelctall.setRowCount(0)
        self.table_seelctall.horizontalHeader().setVisible(False)
        self.table_seelctall.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.table_seelctall)
        self.txt_result = QtWidgets.QTextBrowser(self.tab_2)
        self.txt_result.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_result.setFont(font)
        self.txt_result.setObjectName("txt_result")
        self.horizontalLayout_4.addWidget(self.txt_result)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gp_find_by_id = QtWidgets.QGroupBox(self.tab_3)
        self.gp_find_by_id.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_find_by_id.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_find_by_id.setObjectName("gp_find_by_id")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gp_find_by_id)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_find_id = QtWidgets.QLabel(self.gp_find_by_id)
        self.lb_find_id.setObjectName("lb_find_id")
        self.verticalLayout_3.addWidget(self.lb_find_id)
        self.et_find_by_id = QtWidgets.QLineEdit(self.gp_find_by_id)
        self.et_find_by_id.setObjectName("et_find_by_id")
        self.verticalLayout_3.addWidget(self.et_find_by_id)
        self.lb_find_name = QtWidgets.QLabel(self.gp_find_by_id)
        self.lb_find_name.setObjectName("lb_find_name")
        self.verticalLayout_3.addWidget(self.lb_find_name)
        self.et_find_name = QtWidgets.QLineEdit(self.gp_find_by_id)
        self.et_find_name.setObjectName("et_find_name")
        self.verticalLayout_3.addWidget(self.et_find_name)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_7.addWidget(self.gp_find_by_id)
        self.table_findbyid = QtWidgets.QTableWidget(self.tab_3)
        self.table_findbyid.setObjectName("table_findbyid")
        self.table_findbyid.setColumnCount(0)
        self.table_findbyid.setRowCount(0)
        self.table_findbyid.horizontalHeader().setVisible(False)
        self.table_findbyid.verticalHeader().setVisible(False)
        self.horizontalLayout_7.addWidget(self.table_findbyid)
        self.txt_findbyid = QtWidgets.QTextBrowser(self.tab_3)
        self.txt_findbyid.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_findbyid.setFont(font)
        self.txt_findbyid.setObjectName("txt_findbyid")
        self.horizontalLayout_7.addWidget(self.txt_findbyid)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gp_customer = QtWidgets.QGroupBox(self.tab_1)
        self.gp_customer.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_customer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_customer.setObjectName("gp_customer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gp_customer)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.gp_customer)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.et_customer_name = QtWidgets.QLineEdit(self.gp_customer)
        self.et_customer_name.setObjectName("et_customer_name")
        self.verticalLayout_7.addWidget(self.et_customer_name)
        self.label_10 = QtWidgets.QLabel(self.gp_customer)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.et_customer_city = QtWidgets.QLineEdit(self.gp_customer)
        self.et_customer_city.setObjectName("et_customer_city")
        self.verticalLayout_7.addWidget(self.et_customer_city)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.gp_customer)
        self.gp_agency = QtWidgets.QGroupBox(self.tab_1)
        self.gp_agency.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_agency.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_agency.setObjectName("gp_agency")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gp_agency)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.gp_agency)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.et_ag_name = QtWidgets.QLineEdit(self.gp_agency)
        self.et_ag_name.setObjectName("et_ag_name")
        self.verticalLayout_6.addWidget(self.et_ag_name)
        self.label_7 = QtWidgets.QLabel(self.gp_agency)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.et_ag_city = QtWidgets.QLineEdit(self.gp_agency)
        self.et_ag_city.setObjectName("et_ag_city")
        self.verticalLayout_6.addWidget(self.et_ag_city)
        self.label_8 = QtWidgets.QLabel(self.gp_agency)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.et_ag_active = QtWidgets.QLineEdit(self.gp_agency)
        self.et_ag_active.setObjectName("et_ag_active")
        self.verticalLayout_6.addWidget(self.et_ag_active)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.gp_agency)
        self.gp_account = QtWidgets.QGroupBox(self.tab_1)
        self.gp_account.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_account.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_account.setObjectName("gp_account")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gp_account)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.gp_account)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.et_account_num_agency = QtWidgets.QLineEdit(self.gp_account)
        self.et_account_num_agency.setObjectName("et_account_num_agency")
        self.verticalLayout_8.addWidget(self.et_account_num_agency)
        self.label_13 = QtWidgets.QLabel(self.gp_account)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.et_account_num_customer = QtWidgets.QLineEdit(self.gp_account)
        self.et_account_num_customer.setObjectName("et_account_num_customer")
        self.verticalLayout_8.addWidget(self.et_account_num_customer)
        self.label_14 = QtWidgets.QLabel(self.gp_account)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_8.addWidget(self.label_14)
        self.et_account_account = QtWidgets.QLineEdit(self.gp_account)
        self.et_account_account.setObjectName("et_account_account")
        self.verticalLayout_8.addWidget(self.et_account_account)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.gp_account)
        self.gp_loan = QtWidgets.QGroupBox(self.tab_1)
        self.gp_loan.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_loan.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_loan.setObjectName("gp_loan")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gp_loan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.gp_loan)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.et_loan_num_agency = QtWidgets.QLineEdit(self.gp_loan)
        self.et_loan_num_agency.setObjectName("et_loan_num_agency")
        self.verticalLayout_2.addWidget(self.et_loan_num_agency)
        self.label_15 = QtWidgets.QLabel(self.gp_loan)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.et_loan_num_customer = QtWidgets.QLineEdit(self.gp_loan)
        self.et_loan_num_customer.setObjectName("et_loan_num_customer")
        self.verticalLayout_2.addWidget(self.et_loan_num_customer)
        self.label_16 = QtWidgets.QLabel(self.gp_loan)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.et_loan_amount = QtWidgets.QLineEdit(self.gp_loan)
        self.et_loan_amount.setObjectName("et_loan_amount")
        self.verticalLayout_2.addWidget(self.et_loan_amount)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_2.addWidget(self.gp_loan)
        self.gp_insert_user = QtWidgets.QGroupBox(self.tab_1)
        self.gp_insert_user.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_insert_user.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_insert_user.setObjectName("gp_insert_user")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.gp_insert_user)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_37 = QtWidgets.QLabel(self.gp_insert_user)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_16.addWidget(self.label_37)
        self.et_user_login = QtWidgets.QLineEdit(self.gp_insert_user)
        self.et_user_login.setObjectName("et_user_login")
        self.verticalLayout_16.addWidget(self.et_user_login)
        self.label_38 = QtWidgets.QLabel(self.gp_insert_user)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_16.addWidget(self.label_38)
        self.et_user_pass = QtWidgets.QLineEdit(self.gp_insert_user)
        self.et_user_pass.setObjectName("et_user_pass")
        self.verticalLayout_16.addWidget(self.et_user_pass)
        self.label_39 = QtWidgets.QLabel(self.gp_insert_user)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.et_user_admin = QtWidgets.QLineEdit(self.gp_insert_user)
        self.et_user_admin.setObjectName("et_user_admin")
        self.verticalLayout_16.addWidget(self.et_user_admin)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem8)
        self.horizontalLayout_2.addWidget(self.gp_insert_user)
        self.txt_result_insert = QtWidgets.QTextBrowser(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_result_insert.setFont(font)
        self.txt_result_insert.setObjectName("txt_result_insert")
        self.horizontalLayout_2.addWidget(self.txt_result_insert)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gp_update_agenacy = QtWidgets.QGroupBox(self.tab_4)
        self.gp_update_agenacy.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_update_agenacy.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_update_agenacy.setObjectName("gp_update_agenacy")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gp_update_agenacy)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gp_update_agenacy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.et_update_agency = QtWidgets.QLineEdit(self.gp_update_agenacy)
        self.et_update_agency.setObjectName("et_update_agency")
        self.verticalLayout_4.addWidget(self.et_update_agency)
        self.label_2 = QtWidgets.QLabel(self.gp_update_agenacy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.et_update_agency_name = QtWidgets.QLineEdit(self.gp_update_agenacy)
        self.et_update_agency_name.setObjectName("et_update_agency_name")
        self.verticalLayout_4.addWidget(self.et_update_agency_name)
        self.label_23 = QtWidgets.QLabel(self.gp_update_agenacy)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.et_update_agency_city = QtWidgets.QLineEdit(self.gp_update_agenacy)
        self.et_update_agency_city.setObjectName("et_update_agency_city")
        self.verticalLayout_4.addWidget(self.et_update_agency_city)
        self.label_24 = QtWidgets.QLabel(self.gp_update_agenacy)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.et_update_agency_active = QtWidgets.QLineEdit(self.gp_update_agenacy)
        self.et_update_agency_active.setObjectName("et_update_agency_active")
        self.verticalLayout_4.addWidget(self.et_update_agency_active)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_6.addWidget(self.gp_update_agenacy)
        self.gp_update_customer = QtWidgets.QGroupBox(self.tab_4)
        self.gp_update_customer.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_update_customer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_update_customer.setObjectName("gp_update_customer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gp_update_customer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.gp_update_customer)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.et_update_customer = QtWidgets.QLineEdit(self.gp_update_customer)
        self.et_update_customer.setObjectName("et_update_customer")
        self.verticalLayout_9.addWidget(self.et_update_customer)
        self.label_25 = QtWidgets.QLabel(self.gp_update_customer)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_9.addWidget(self.label_25)
        self.et_update_customer_name = QtWidgets.QLineEdit(self.gp_update_customer)
        self.et_update_customer_name.setObjectName("et_update_customer_name")
        self.verticalLayout_9.addWidget(self.et_update_customer_name)
        self.label_26 = QtWidgets.QLabel(self.gp_update_customer)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.et_update_customer_city = QtWidgets.QLineEdit(self.gp_update_customer)
        self.et_update_customer_city.setObjectName("et_update_customer_city")
        self.verticalLayout_9.addWidget(self.et_update_customer_city)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.horizontalLayout_6.addWidget(self.gp_update_customer)
        self.gp_update_account = QtWidgets.QGroupBox(self.tab_4)
        self.gp_update_account.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_update_account.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_update_account.setObjectName("gp_update_account")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gp_update_account)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.gp_update_account)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.et_update_account = QtWidgets.QLineEdit(self.gp_update_account)
        self.et_update_account.setObjectName("et_update_account")
        self.verticalLayout_10.addWidget(self.et_update_account)
        self.label_27 = QtWidgets.QLabel(self.gp_update_account)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.et_update_account_agency = QtWidgets.QLineEdit(self.gp_update_account)
        self.et_update_account_agency.setObjectName("et_update_account_agency")
        self.verticalLayout_10.addWidget(self.et_update_account_agency)
        self.label_28 = QtWidgets.QLabel(self.gp_update_account)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.et_update_account_customer = QtWidgets.QLineEdit(self.gp_update_account)
        self.et_update_account_customer.setObjectName("et_update_account_customer")
        self.verticalLayout_10.addWidget(self.et_update_account_customer)
        self.label_29 = QtWidgets.QLabel(self.gp_update_account)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_10.addWidget(self.label_29)
        self.et_update_account_balanc = QtWidgets.QLineEdit(self.gp_update_account)
        self.et_update_account_balanc.setObjectName("et_update_account_balanc")
        self.verticalLayout_10.addWidget(self.et_update_account_balanc)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.horizontalLayout_6.addWidget(self.gp_update_account)
        self.gp_update_loan = QtWidgets.QGroupBox(self.tab_4)
        self.gp_update_loan.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_update_loan.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_update_loan.setObjectName("gp_update_loan")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.gp_update_loan)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.gp_update_loan)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_11.addWidget(self.label_19)
        self.et_update_loan = QtWidgets.QLineEdit(self.gp_update_loan)
        self.et_update_loan.setObjectName("et_update_loan")
        self.verticalLayout_11.addWidget(self.et_update_loan)
        self.label_30 = QtWidgets.QLabel(self.gp_update_loan)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_11.addWidget(self.label_30)
        self.et_update_loan_agency = QtWidgets.QLineEdit(self.gp_update_loan)
        self.et_update_loan_agency.setObjectName("et_update_loan_agency")
        self.verticalLayout_11.addWidget(self.et_update_loan_agency)
        self.label_31 = QtWidgets.QLabel(self.gp_update_loan)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_11.addWidget(self.label_31)
        self.et_update_loan_customer = QtWidgets.QLineEdit(self.gp_update_loan)
        self.et_update_loan_customer.setObjectName("et_update_loan_customer")
        self.verticalLayout_11.addWidget(self.et_update_loan_customer)
        self.label_32 = QtWidgets.QLabel(self.gp_update_loan)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_11.addWidget(self.label_32)
        self.et_update_loan_amount = QtWidgets.QLineEdit(self.gp_update_loan)
        self.et_update_loan_amount.setObjectName("et_update_loan_amount")
        self.verticalLayout_11.addWidget(self.et_update_loan_amount)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.horizontalLayout_6.addWidget(self.gp_update_loan)
        self.gp_update_user = QtWidgets.QGroupBox(self.tab_4)
        self.gp_update_user.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_update_user.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_update_user.setObjectName("gp_update_user")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gp_update_user)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_44 = QtWidgets.QLabel(self.gp_update_user)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_17.addWidget(self.label_44)
        self.et_update_user_Id = QtWidgets.QLineEdit(self.gp_update_user)
        self.et_update_user_Id.setObjectName("et_update_user_Id")
        self.verticalLayout_17.addWidget(self.et_update_user_Id)
        self.label_40 = QtWidgets.QLabel(self.gp_update_user)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_17.addWidget(self.label_40)
        self.et_update_user_login = QtWidgets.QLineEdit(self.gp_update_user)
        self.et_update_user_login.setObjectName("et_update_user_login")
        self.verticalLayout_17.addWidget(self.et_update_user_login)
        self.label_41 = QtWidgets.QLabel(self.gp_update_user)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_17.addWidget(self.label_41)
        self.et_update_user_pass = QtWidgets.QLineEdit(self.gp_update_user)
        self.et_update_user_pass.setObjectName("et_update_user_pass")
        self.verticalLayout_17.addWidget(self.et_update_user_pass)
        self.label_42 = QtWidgets.QLabel(self.gp_update_user)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_17.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.gp_update_user)
        self.label_43.setFrameShape(QtWidgets.QFrame.Box)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_17.addWidget(self.label_43)
        self.et_update_user_admin = QtWidgets.QLineEdit(self.gp_update_user)
        self.et_update_user_admin.setObjectName("et_update_user_admin")
        self.verticalLayout_17.addWidget(self.et_update_user_admin)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem13)
        self.horizontalLayout_6.addWidget(self.gp_update_user)
        self.txt_update = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_update.setFont(font)
        self.txt_update.setObjectName("txt_update")
        self.horizontalLayout_6.addWidget(self.txt_update)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gp_delete_agency = QtWidgets.QGroupBox(self.tab_5)
        self.gp_delete_agency.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_delete_agency.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_delete_agency.setObjectName("gp_delete_agency")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gp_delete_agency)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gp_delete_agency)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.et_delete_agancy = QtWidgets.QLineEdit(self.gp_delete_agency)
        self.et_delete_agancy.setObjectName("et_delete_agancy")
        self.verticalLayout_5.addWidget(self.et_delete_agancy)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_5.addWidget(self.gp_delete_agency)
        self.gp_delete_customer = QtWidgets.QGroupBox(self.tab_5)
        self.gp_delete_customer.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_delete_customer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_delete_customer.setObjectName("gp_delete_customer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.gp_delete_customer)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.gp_delete_customer)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_12.addWidget(self.label_20)
        self.et_delete_customer = QtWidgets.QLineEdit(self.gp_delete_customer)
        self.et_delete_customer.setObjectName("et_delete_customer")
        self.verticalLayout_12.addWidget(self.et_delete_customer)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem15)
        self.horizontalLayout_5.addWidget(self.gp_delete_customer)
        self.gp_delete_account = QtWidgets.QGroupBox(self.tab_5)
        self.gp_delete_account.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_delete_account.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_delete_account.setObjectName("gp_delete_account")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.gp_delete_account)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.gp_delete_account)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.et_delete_active = QtWidgets.QLineEdit(self.gp_delete_account)
        self.et_delete_active.setObjectName("et_delete_active")
        self.verticalLayout_13.addWidget(self.et_delete_active)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.horizontalLayout_5.addWidget(self.gp_delete_account)
        self.gp_delete_loan = QtWidgets.QGroupBox(self.tab_5)
        self.gp_delete_loan.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_delete_loan.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_delete_loan.setObjectName("gp_delete_loan")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.gp_delete_loan)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.gp_delete_loan)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_14.addWidget(self.label_22)
        self.et_delete_loan = QtWidgets.QLineEdit(self.gp_delete_loan)
        self.et_delete_loan.setObjectName("et_delete_loan")
        self.verticalLayout_14.addWidget(self.et_delete_loan)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem17)
        self.horizontalLayout_5.addWidget(self.gp_delete_loan)
        self.gp_delete_user = QtWidgets.QGroupBox(self.tab_5)
        self.gp_delete_user.setMinimumSize(QtCore.QSize(200, 0))
        self.gp_delete_user.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gp_delete_user.setObjectName("gp_delete_user")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.gp_delete_user)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_46 = QtWidgets.QLabel(self.gp_delete_user)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_19.addWidget(self.label_46)
        self.et_delete_user = QtWidgets.QLineEdit(self.gp_delete_user)
        self.et_delete_user.setObjectName("et_delete_user")
        self.verticalLayout_19.addWidget(self.et_delete_user)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem18)
        self.horizontalLayout_5.addWidget(self.gp_delete_user)
        self.txt_delete = QtWidgets.QTextBrowser(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_delete.setFont(font)
        self.txt_delete.setObjectName("txt_delete")
        self.horizontalLayout_5.addWidget(self.txt_delete)
        self.tabWidget.addTab(self.tab_5, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1475, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Login Page"))
        self.label_33.setText(_translate("MainWindow", "User Name:"))
        self.label_34.setText(_translate("MainWindow", "Password:"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.groupBox.setTitle(_translate("MainWindow", "Parameter"))
        self.lable_login_name.setText(_translate("MainWindow", "Welcome"))
        self.label.setText(_translate("MainWindow", "Choose table name:"))
        self.cm_database.setItemText(0, _translate("MainWindow", "Select Table..."))
        self.cm_database.setItemText(1, _translate("MainWindow", "Agency"))
        self.cm_database.setItemText(2, _translate("MainWindow", "Customer"))
        self.cm_database.setItemText(3, _translate("MainWindow", "Account"))
        self.cm_database.setItemText(4, _translate("MainWindow", "Loan"))
        self.cm_database.setItemText(5, _translate("MainWindow", "User"))
        self.btn_process.setText(_translate("MainWindow", "Process"))
        self.btn_save_excel.setText(_translate("MainWindow", "Save as Excel"))
        self.btn_logout.setText(_translate("MainWindow", "Log Out"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result"))
        self.label_3.setText(_translate("MainWindow", "Offset"))
        self.label_45.setText(_translate("MainWindow", "Limit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SelectAll"))
        self.gp_find_by_id.setTitle(_translate("MainWindow", "Find by id"))
        self.lb_find_id.setText(_translate("MainWindow", "Enter id number"))
        self.lb_find_name.setText(_translate("MainWindow", "Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Find By Id"))
        self.gp_customer.setTitle(_translate("MainWindow", "Insert Customer"))
        self.label_9.setText(_translate("MainWindow", "Name:"))
        self.label_10.setText(_translate("MainWindow", "City:"))
        self.gp_agency.setTitle(_translate("MainWindow", "Insert Agency"))
        self.label_6.setText(_translate("MainWindow", "Name:"))
        self.label_7.setText(_translate("MainWindow", "City:"))
        self.label_8.setText(_translate("MainWindow", "Active:"))
        self.gp_account.setTitle(_translate("MainWindow", "Insert Account"))
        self.label_11.setText(_translate("MainWindow", "Num Agency:"))
        self.label_13.setText(_translate("MainWindow", "Num customer:"))
        self.label_14.setText(_translate("MainWindow", "Balanc"))
        self.gp_loan.setTitle(_translate("MainWindow", "Insert Loan"))
        self.label_12.setText(_translate("MainWindow", "Num Agency:"))
        self.label_15.setText(_translate("MainWindow", "Num Customer:"))
        self.label_16.setText(_translate("MainWindow", "Amount"))
        self.gp_insert_user.setTitle(_translate("MainWindow", "Insert User"))
        self.label_37.setText(_translate("MainWindow", "Login"))
        self.label_38.setText(_translate("MainWindow", "Password"))
        self.label_39.setText(_translate("MainWindow", "Admin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Insert"))
        self.gp_update_agenacy.setTitle(_translate("MainWindow", "Update Agency"))
        self.label_4.setText(_translate("MainWindow", "Enter Num_agency"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_23.setText(_translate("MainWindow", "City"))
        self.label_24.setText(_translate("MainWindow", "Active"))
        self.gp_update_customer.setTitle(_translate("MainWindow", "Update Customer"))
        self.label_17.setText(_translate("MainWindow", "Enter Num_customer"))
        self.label_25.setText(_translate("MainWindow", "Name"))
        self.label_26.setText(_translate("MainWindow", "City"))
        self.gp_update_account.setTitle(_translate("MainWindow", "Update Account"))
        self.label_18.setText(_translate("MainWindow", "Enter Num_account"))
        self.label_27.setText(_translate("MainWindow", "Num Agency:"))
        self.label_28.setText(_translate("MainWindow", "Num customer:"))
        self.label_29.setText(_translate("MainWindow", "Balanc:"))
        self.gp_update_loan.setTitle(_translate("MainWindow", "Update Loan"))
        self.label_19.setText(_translate("MainWindow", "EnterNum_loan"))
        self.label_30.setText(_translate("MainWindow", "Num Agency:"))
        self.label_31.setText(_translate("MainWindow", "Num Customer:"))
        self.label_32.setText(_translate("MainWindow", "Amount"))
        self.gp_update_user.setTitle(_translate("MainWindow", "Update user"))
        self.label_44.setText(_translate("MainWindow", "Id"))
        self.label_40.setText(_translate("MainWindow", "Login"))
        self.label_41.setText(_translate("MainWindow", "Password"))
        self.label_42.setText(_translate("MainWindow", "Admin"))
        self.label_43.setText(_translate("MainWindow", "For admin you should insert 1 \n"
" and for customer insert 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Update"))
        self.gp_delete_agency.setTitle(_translate("MainWindow", "Delete Agency"))
        self.label_5.setText(_translate("MainWindow", "Enter id number"))
        self.gp_delete_customer.setTitle(_translate("MainWindow", "Delete Customer"))
        self.label_20.setText(_translate("MainWindow", "Enter id number"))
        self.gp_delete_account.setTitle(_translate("MainWindow", "Delete Account"))
        self.label_21.setText(_translate("MainWindow", "Enter id number"))
        self.gp_delete_loan.setTitle(_translate("MainWindow", "Delete Loan"))
        self.label_22.setText(_translate("MainWindow", "Enter id number"))
        self.gp_delete_user.setTitle(_translate("MainWindow", "Delete User"))
        self.label_46.setText(_translate("MainWindow", "Enter user id"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
